name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/packages/zk-tron-contracts
          key: poetry-cache-${{ env.PYTHON_VERSION }}-${{ hashFiles('packages/**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - run: npm run lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/cobertura.xml
